github:
  features:
    # Enable issue management
    issues: true
  description: " .asf.yaml documentation and schema "
  homepage: https://infra.apache.org/
  labels:
    - apache
    - selfserve
    - yaml
    - git
    - github
  autolink_jira:
    - INFRA
notifications:
  jobs:         notifications@infra.apache.org
  jira_options: link label comment
