name: Validator Unit Tests

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0 # need all versions to be able to access server tree commit logs
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt -y install python3-dev
          python3 -m pip install --upgrade poetry
          poetry install
          python3 -m pip install pylint
          python3 -m pip install mypy
          python3 -m pip install types-requests
          python3 -m pip install yaml
          python3 -m pip install PyYAML
      - name: Test with pytest
        run: |
          poetry run python3 -m pytest tests/*.py
      - name: Type testing with mypy
        if: always() # even if pytest fails
        run: |
            mypy --cache-dir /tmp/ --install-types
            mypy --cache-dir /tmp/ --ignore-missing-imports *.py feature/*.py tests/*.py
      - name: Testing with pylint
        if: always() # even if mypy fails
        run: |
            pylint --recursive y .
